name             'realmd-sssd'
maintainer       'John Bartko'
maintainer_email 'jbartko@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures realmd-sssd'
long_description 'Installs/Configures realmd-sssd'
version          '0.1.0'

depends 'apt'
depends 'chef-vault'
depends 'openssh'
depends 'yum'
